# Mage2click Docker Configuration for Magento 2 with Mutagen.io sync (https://github.com/mage2click/docker-magento-mutagen)
# Version 1.0.0

version: "3"

services:

  app:
    image: mage2click/magento-nginx:1.13
    ports:
      - "80:8000"
      - "443:8443"
    depends_on:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock

  phpfpm:
    image: mage2click/magento-php:7.1-fpm-mailhog
    depends_on:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  cron:
    image: mage2click/magento-php:7.1-fpm
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  sockdata:
